//
// Created by ASUS FX506HC on 21/11/2025.
//

#ifndef PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_ESCUDOBENDITO_H
#define PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_ESCUDOBENDITO_H


class EscudoBendito {
};


#endif //PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_ESCUDOBENDITO_H