//
// Created by ASUS FX506HC on 21/11/2025.
//

#ifndef PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_POCIONVIDA_H
#define PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_POCIONVIDA_H


class PocionVida {
};


#endif //PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_END_POCIONVIDA_H